from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

class Department(models.Model):
    name = models.CharField(max_length=100)

class Designation(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()

class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('admin', 'Admin'),
        ('team_leader', 'Team Leader'),
        ('normal_user', 'Normal User'),
    )
    role = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)

class UserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name="user")   
    user_profile_pic = models.FileField(upload_to='uploads/', default="")
    transaction_number = models.CharField(max_length=50, null=True, default="")
    user_enabled = models.CharField(max_length=1, null=True, default="")
    user_title = models.CharField(max_length=20, null=True, default="")
    user_fname = models.CharField(max_length=100, null=True, default="")
    user_mname = models.CharField(max_length=100, null=True, default="")
    user_lname = models.CharField(max_length=100, null=True, default="")
    user_full_name = models.CharField(max_length=150, null=True, default="")
    user_address1 = models.TextField(null=True, default="")
    user_address2 = models.TextField(null=True, default="")
    user_address3 = models.TextField(null=True, default="")
    user_city_code = models.CharField(max_length=100, null=True, default="")
    user_zip_code = models.CharField(max_length=100, null=True, default="")
    user_state_code = models.CharField(max_length=100, null=True, default="")
    user_country_code = models.CharField(max_length=100, null=True, default="")
    user_birthday = models.DateField(null=True, default=None)
    user_anniversary = models.DateField(null=True, default=None)
    user_dept_id = models.ForeignKey(Department, on_delete=models.DO_NOTHING, related_name="department", null=True, blank=True)
    user_desig_id = models.ForeignKey(Designation, on_delete=models.DO_NOTHING, related_name="designation", null=True, blank=True)
    user_team_id = models.IntegerField(null=True, default=None) # add team id
    user_seniority = models.CharField(max_length=100, null=True, default="")
    user_profession = models.CharField(max_length=100, null=True, default="")
    user_manager = models.CharField(max_length=100, null=True, default="")
    user_extension = models.BigIntegerField(null=True, default=None)
    created_by = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, related_name="created_by", null=True, blank=True)
    created_DateField = models.DateField(null=True, default=None)
    modified_by = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, related_name="mordified_by", null=True, blank=True)
    modified_DateField = models.DateField(null=True, default=None)
    last_activity_DateField = models.DateField(null=True, default=None)
    user_timezone_id = models.IntegerField(null=True, default=None)
    user_timezone_timespan = models.IntegerField(null=True, default=None)
    user_login_id = models.CharField(max_length=100, null=True, default="")
    user_password = models.CharField(max_length=100, null=True, default="")
    user_current_theme = models.CharField(max_length=100, null=True, default="")
    user_phone = models.CharField(max_length=100, null=True, default="")
    user_emailid = models.CharField(max_length=100, null=True, default="")
    user_role = models.CharField(max_length=100, null=True, default="")
    cust_reportingtocolumn = models.CharField(max_length=100, null=True, default="")
    user_joingDateField = models.DateField(null=True, default=None)
    user_LastworkingDateField = models.DateField(null=True, default=None)
    user_contractstartDateField = models.DateField(null=True, default=None)
    user_contractendDateField = models.DateField(null=True, default=None)
    user_materialstatus = models.CharField(max_length=100, null=True, default="")
    user_gender = models.CharField(max_length=100, null=True, default="")
    user_emergencydetails = models.CharField(max_length=100, null=True, default="")
    user_project = models.CharField(max_length=100, null=True, default="")
    user_usersType = models.CharField(max_length=100, null=True, default="")
    user_educationalStatus = models.CharField(max_length=100, null=True, default="")
    user_bloodGrp = models.CharField(max_length=100, null=True, default="")
    user_NRCNo = models.CharField(max_length=100, null=True, default="")
    user_nationality = models.CharField(max_length=100, null=True, default="")
    user_Region = models.CharField(max_length=100, null=True, default="")
    user_basicSalary = models.CharField(max_length=100, null=True, default="")
    user_PersonalPay = models.CharField(max_length=100, null=True, default="")
    user_GrossSalary = models.CharField(max_length=100, null=True, default="")
    user_expect = models.CharField(max_length=100, null=True, default="")
    user_contractTerms = models.CharField(max_length=100, null=True, default="")
    user_personalemailid = models.CharField(max_length=100, null=True, default="")
    user_personalphone = models.CharField(max_length=100, null=True, default="")
    user_bankname = models.CharField(max_length=100, null=True, default="")
    user_bankAccountNo = models.CharField(max_length=100, null=True, default="")
    user_EmployeeSSB = models.CharField(max_length=100, null=True, default="")
    user_EmployerSSB = models.CharField(max_length=100, null=True, default="")
    user_ssnnumber = models.CharField(max_length=100, null=True, default="")
    user_taxslab = models.CharField(max_length=100, null=True, default="")
    user_educationdetails = models.CharField(max_length=100, null=True, default="")
    user_Parents = models.CharField(max_length=100, null=True, default="")
    user_Children = models.CharField(max_length=100, null=True, default="")
    user_code = models.CharField(max_length=50, null=True, default="")
    user_dob = models.DateField(null=True, default=None)
    user_InActiveStatus = models.CharField(max_length=100, null=True, default="")
    user_TerminationRemarks = models.CharField(max_length=1000, null=True, default="")
    user_mothername = models.CharField(max_length=100, null=True, default="")
    user_wifename = models.CharField(max_length=100, null=True, default="")
    user_wifejob = models.CharField(max_length=100, null=True, default="")
    user_childname = models.CharField(max_length=100, null=True, default="")
    user_parentPhone = models.CharField(max_length=100, null=True, default="")
    user_ProbationstartDateField = models.DateField(null=True, default=None)
    user_ProbationEndDateField = models.DateField(null=True, default=None)
    user_project_lob = models.CharField(max_length=100, null=True, default="")
    user_PAN = models.CharField(max_length=100, null=True, default="")
    user_hra = models.CharField(max_length=100, null=True, default="")
    user_eduqualification = models.CharField(max_length=100, null=True, default="")
    user_Place = models.CharField(max_length=100, null=True, default="")
    user_WFH_WFO = models.CharField(max_length=100, null=True, default="")
    user_TrainingStart = models.DateField(null=True, default=None)
    user_TrainingEnd = models.DateField(null=True, default=None)
    user_ifsccode = models.CharField(max_length=100, null=True, default="")
    user_Category = models.CharField(max_length=100, null=True, default="")
    user_FloorStatus = models.CharField(max_length=100, null=True, default="")
    user_Tenure = models.CharField(max_length=100, null=True, default="")
    user_TenureBucket = models.CharField(max_length=100, null=True, default="")
    user_BroadbandSystem = models.CharField(max_length=100, null=True, default="")
    user_FT_PT = models.CharField(max_length=100, null=True, default="")
    user_Age = models.CharField(max_length=100, null=True, default="")
    user_AgeGroup = models.CharField(max_length=100, null=True, default="")
    user_FatherHusbandName = models.CharField(max_length=100, null=True, default="")
    user_GuardianName = models.CharField(max_length=100, null=True, default="")
    user_GuardianNo = models.CharField(max_length=100, null=True, default="")
    user_Referance1 = models.CharField(max_length=100, null=True, default="")
    user_Referance2 = models.CharField(max_length=100, null=True, default="")
    user_Referance1_No = models.CharField(max_length=100, null=True, default="")
    user_Referance2_No = models.CharField(max_length=100, null=True, default="")
    user_EmergencyuserNo = models.CharField(max_length=100, null=True, default="")
    user_EduCategory = models.CharField(max_length=100, null=True, default="")
    user_University = models.CharField(max_length=100, null=True, default="")
    user_CompletionYear = models.CharField(max_length=100, null=True, default="")
    user_Religion = models.CharField(max_length=100, null=True, default="")
    user_BloodGroup = models.CharField(max_length=100, null=True, default="")
    user_Fresher = models.CharField(max_length=100, null=True, default="")
    user_PreviosuOrg = models.CharField(max_length=100, null=True, default="")
    user_TotalExp = models.CharField(max_length=100, null=True, default="")
    user_SourceType = models.CharField(max_length=100, null=True, default="")
    user_SourceName = models.CharField(max_length=100, null=True, default="")
    user_LanguageKnows = models.CharField(max_length=100, null=True, default="")
    user_UANApplicability = models.CharField(max_length=100, null=True, default="")
    user_ESIApplicability = models.CharField(max_length=100, null=True, default="")
    user_UANNo = models.CharField(max_length=100, null=True, default="")
    user_ESINo = models.CharField(max_length=100, null=True, default="")
    user_Incentive = models.CharField(max_length=100, null=True, default="")
    user_Bonus = models.CharField(max_length=100, null=True, default="")
    user_SubTotal = models.CharField(max_length=100, null=True, default="")
    user_PFCompany = models.CharField(max_length=100, null=True, default="")
    user_ESICompany = models.CharField(max_length=100, null=True, default="")
    user_PFEmployee = models.CharField(max_length=100, null=True, default="")
    user_ESIEmployee = models.CharField(max_length=100, null=True, default="")
    user_Gratuity = models.CharField(max_length=100, null=True, default="")
    user_Variable = models.CharField(max_length=100, null=True, default="")
    user_PT = models.CharField(max_length=100, null=True, default="")
    user_CTC = models.CharField(max_length=100, null=True, default="")
    user_Inhand = models.CharField(max_length=100, null=True, default="")
    user_InactiveBucket = models.CharField(max_length=100, null=True, default="")
    user_AttritionBucket = models.CharField(max_length=100, null=True, default="")
    user_SeparationRemark = models.CharField(max_length=100, null=True, default="")
    user_RehireStatus = models.CharField(max_length=100, null=True, default="")

    def __str__(self):
        return str(self.user_full_name)

@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.user.save()
    except UserProfile.DoesNotExist:
        pass
